[package]
name = "smithy-language-server-zed-extension"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/smithy_language_server.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
